CREATE TABLE produtos (
                          id_produto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome VARCHAR(150) NOT NULL UNIQUE,
                          categoria VARCHAR(20) NOT NULL,
                          estoque_atual INT NOT NULL,
                          estoque_minimo INT NOT NULL,
                          unidade_medida VARCHAR(20) NOT NULL,
                          data_cadastro DATE NOT NULL,
                          CONSTRAINT chk_estoque_atual_nao_negativo CHECK (estoque_atual >= 0),
                          CONSTRAINT chk_estoque_minimo_nao_negativo CHECK (estoque_minimo >= 0)
);
CREATE INDEX idx_produtos_nome ON produtos(nome);
CREATE INDEX idx_produtos_categoria ON produtos(categoria);